//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarlemErpDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public clientes()
        {
            this.vendas = new HashSet<vendas>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> datanascimento { get; set; }
        public string sexo { get; set; }
        public string rg { get; set; }
        public string cpf { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public string celular { get; set; }
        public string logradouro { get; set; }
        public string complemento { get; set; }
        public Nullable<int> numero { get; set; }
        public string bairro { get; set; }
        public string cep { get; set; }
        public Nullable<int> municipio { get; set; }
        public Nullable<System.DateTime> datacadastro { get; set; }
        public int usuariocadastro { get; set; }
    
        public virtual municipios municipios { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual ICollection<vendas> vendas { get; set; }
    }
}
