//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarlemErpDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class estoque
    {
        public int id { get; set; }
        public int produto { get; set; }
        public double qtd { get; set; }
    
        public virtual produtos produtos { get; set; }
    }
}
