//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarlemErpDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class marcas
    {
        public marcas()
        {
            this.produtos = new HashSet<produtos>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> datacadastro { get; set; }
        public int usuariocadastro { get; set; }
    
        public virtual usuarios usuarios { get; set; }
        public virtual ICollection<produtos> produtos { get; set; }
    }
}
