//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarlemErpDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class municipios
    {
        public municipios()
        {
            this.clientes = new HashSet<clientes>();
        }
    
        public int id { get; set; }
        public int estado { get; set; }
        public string nome { get; set; }
    
        public virtual ICollection<clientes> clientes { get; set; }
        public virtual estados estados { get; set; }
    }
}
