//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarlemErpDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class precos
    {
        public int id { get; set; }
        public int produto { get; set; }
        public System.DateTime datainicial { get; set; }
        public Nullable<System.DateTime> datafinal { get; set; }
        public double valorcusto { get; set; }
        public double valorvenda { get; set; }
        public Nullable<System.DateTime> datacadastro { get; set; }
        public Nullable<int> usuariocadastro { get; set; }
    
        public virtual produtos produtos { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
