//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarlemErpDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public usuarios()
        {
            this.clientes = new HashSet<clientes>();
            this.marcas = new HashSet<marcas>();
            this.precos = new HashSet<precos>();
            this.produtos = new HashSet<produtos>();
            this.vendas = new HashSet<vendas>();
        }
    
        public int id { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
    
        public virtual ICollection<clientes> clientes { get; set; }
        public virtual ICollection<marcas> marcas { get; set; }
        public virtual ICollection<precos> precos { get; set; }
        public virtual ICollection<produtos> produtos { get; set; }
        public virtual ICollection<vendas> vendas { get; set; }
    }
}
